# Echidna Configuration for Vereavement Protocol
# This file configures Echidna fuzzing for the Sarcophagus contract

# Test mode: assertion, optimization, or exploration
testMode: assertion

# Number of test cases to generate
testLimit: 50000

# Directory to store corpus (test cases)
corpusDir: corpus

# Enable coverage tracking
coverage: true

# Output format
format: text

# Contract to test
contract: Sarcophagus

# Deployer address (Hardhat default)
deployer: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

# Sender addresses for testing
sender: 
  - "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"  # owner
  - "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"  # user1
  - "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"  # user2
  - "0x90F79bf6EB2c4f870365E785982E1f101E93b906"  # user3
  - "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65"  # oracle

# Gas limit for transactions
gasLimit: 30000000

# Sequence length for test cases
sequenceLength: 100

# Contract addresses (will be filled during deployment)
contractAddr: "0x0000000000000000000000000000000000000000"
deployer: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

# Custom initialization
# init: "echidna-init.sol"

# Custom configuration for specific functions
# functions:
#   - name: "depositTokens"
#     maxGas: 1000000
#   - name: "claimInheritance"
#     maxGas: 2000000 