require('dotenv').config();
const { thorify } = require('thorify');
const Web3 = require('web3');

async function main() {
  console.log("💰 Transferring funds to an address you control...");
  
  const MNEMONIC = process.env.MNEMONIC;
  const FUNDED_ADDRESS = "0x9027A597D2A7cBBc54Cd8905f94e8B8Bd4cFe3Fc";
  
  // Initialize Web3 with Thorify
  const web3 = thorify(new Web3(), "https://testnet.veblocks.net");
  
  // Get the address that your mnemonic generates
  const hdNode = web3.eth.accounts.wallet.create(1, MNEMONIC);
  const controlledAddress = hdNode[0];
  web3.eth.accounts.wallet.add(controlledAddress);
  
  console.log("Funded address:", FUNDED_ADDRESS);
  console.log("Your controlled address:", controlledAddress.address);
  
  // Check balances
  const fundedBalance = await web3.eth.getBalance(FUNDED_ADDRESS);
  const controlledBalance = await web3.eth.getBalance(controlledAddress.address);
  
  console.log(`Funded address balance: ${web3.utils.fromWei(fundedBalance, 'ether')} VET`);
  console.log(`Your address balance: ${web3.utils.fromWei(controlledBalance, 'ether')} VET`);
  
  if (web3.utils.toBN(fundedBalance).eq(web3.utils.toBN(0))) {
    console.log("❌ No funds in the funded address");
    return;
  }
  
  console.log("\n⚠️  IMPORTANT: To transfer funds, you need the private key for the funded address");
  console.log("Since the funded address is not generated by your current mnemonic, you have a few options:");
  
  console.log("\nOption 1: Check if you have a different mnemonic");
  console.log("- The funded address might be from a different wallet/mnemonic");
  console.log("- Check your other wallets or mnemonic backups");
  
  console.log("\nOption 2: Use a different wallet");
  console.log("- Try importing the mnemonic into VeWorld, MetaMask, or another wallet");
  console.log("- See if it generates the funded address there");
  
  console.log("\nOption 3: Get new testnet funds");
  console.log("- Request new testnet VET for your controlled address:", controlledAddress.address);
  console.log("- Go to: https://faucet.vechain.org/");
  
  console.log("\nOption 4: Check if the funded address is accessible");
  console.log("- Try importing the mnemonic into different wallets");
  console.log("- Some wallets might use different derivation methods");
  
  console.log("\n💡 Recommended: Try Option 3 (get new testnet funds) for now");
  console.log("This will let you proceed with deployment immediately");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  }); 